--- 
services: 
  mydb: 
    environment: 
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_USER: wordpress
    image: "mysql:5.7"
    restart: always
    volumes: 
      - "db_data:/var/lib/mysql"
  wordpress: 
    depends_on: 
      - mydb
    environment: 
      WORDPRESS_DB_HOST: "mydb:3306"
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_USER: wordpress
    image: "wordpress:latest"
    ports: 
      - "8000:80"
    restart: always
version: "3.9"
volumes: 
  db_data: {}
